package org.timemates.rrpc.generator.kotlin

internal object Constant {
    val GENERATED_COMMENT = """
        This file is generated by the `rrpcroto/rrpc-kotlin` library.

        WARNING: DO NOT MODIFY THIS FILE MANUALLY!

        Any changes made to this file will be overwritten when the code is regenerated.
    """.trimIndent()
}