@file:OptIn(InternalRSProtoAPI::class)

package org.timemates.rsp.client

import org.timemates.rsp.annotations.InternalRSProtoAPI
import org.timemates.rsp.client.config.RSPClientConfig
import org.timemates.rsp.client.options.RPCsOptions

/**
 * The abstraction for the clients that are generated by `rsproto`.
 */
public abstract class RSPServiceClient(
    config: RSPClientConfig,
) {
    public constructor(
        creator: RSPClientConfig.Builder.() -> Unit,
    ) : this(RSPClientConfig.create(creator))

    /**
     * Responsible for the logic around RSocket for interceptors and request/response data management.
     * No direct access to RSocket is used in the generated code.
     */
    protected val handler: ClientRequestHandler = ClientRequestHandler(config)

    /**
     * Container of the options related to the RPC methods by name.
     * Used and generated internally by the code-generation.
     */
    protected abstract val rpcsOptions: RPCsOptions
}
