package org.timemates.rsp.codegen

internal object Constant {
    val GENERATED_COMMENT = """
        This file is generated by the `rsproto` library.

        WARNING: DO NOT MODIFY THIS FILE MANUALLY!

        Any changes made to this file will be overwritten when the code is regenerated.
    """.trimIndent()
}